export default {
  FETCH_ISSUES_REQUEST: "FETCH_ISSUES_REQUEST",
  FETCH_ISSUES_SUCCESS: "FETCH_ISSUES_SUCCESS",
  FETCH_ISSUES_FAILURE: "FETCH_ISSUES_FAILURE",
  FETCH_ISSUE_BY_ID_REQUEST: "FETCH_ISSUE_BY_ID_REQUEST",
  FETCH_ISSUE_BY_ID_SUCCESS: "FETCH_ISSUE_BY_ID_SUCCESS",
  FETCH_ISSUE_BY_ID_FAILURE: "FETCH_ISSUE_BY_ID_FAILURE",
};
